// <auto-generated />
using Haulmer_Comercio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Haulmer_Comercio.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Haulmer_Comercio.Entidades.Comercios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("puntos")
                        .HasColumnType("int");

                    b.Property<string>("rut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Comercios");
                });

            modelBuilder.Entity("Haulmer_Comercio.Entidades.Ventas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("ComercioId")
                        .HasColumnType("int");

                    b.Property<string>("codigoSeguridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idDispositivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("monto")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ComercioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Haulmer_Comercio.Entidades.Ventas", b =>
                {
                    b.HasOne("Haulmer_Comercio.Entidades.Comercios", "Comercio")
                        .WithMany("ventas")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("Haulmer_Comercio.Entidades.Comercios", b =>
                {
                    b.Navigation("ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
